CREATE TABLE post (ID int generated always as identity, title text, date text, places_to_visit text, description text);



INSERT INTO post (title, date, places_to_visit, description) VALUES ('Explore Utrecht', '09/15/2021', 'Winkel van Sinkel Dance Hall, Bond and Smolders Bakery, Stripwinkel Blunder Comic Store', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
